type GlossaryEntry = [
  word: string,
  meaning: string,
  forms?: string[],
];

export type SentenceVocabulary = {
  word: string;
  meaning: string;
};

const glossary: GlossaryEntry[] = [
  ["earthquake", "地震", ["earthquakes"]],
  ["occur", "発生する、起こる", ["occurs"]],
  ["epicenter", "震央"],
  ["determine", "決定する", ["determined"]],
  ["time lag", "時間差、タイムラグ"],
  ["arrival", "到着"],
  ["P- and S-waves", "P波とS波"],
  ["be proportional to", "～に比例する", ["is proportional to"]],
  ["seismometer", "地震計", ["seismometers"]],
  ["install", "設置する", ["installed"]],
  ["location", "場所、位置", ["locations"]],
  ["Japan Meteorological Agency", "気象庁"],
  ["agency", "庁、機関"],
  ["analyze", "分析する", ["analyzes"]],
  ["data", "データ"],
  ["focus", "震源"],
  ["in order to", "～するために"],
  ["issue", "発令する"],
  ["alert", "警報"],
  ["earthquake early warning", "緊急地震速報"],
  ["let A know", "Aに知らせる", ["lets us know"]],
  ["possibility", "可能性"],
  ["tremor", "揺れ、微動", ["tremors"]],
  ["secondary wave", "S波、第二波"],
  ["close to", "～の近くに"],
  ["arrive", "到着する", ["arrives"]],
  ["warning", "警報"],
  ["protect A from B", "AをBから守る", ["protect yourself from"]],
  ["falling object", "落下物", ["falling objects"]],
  ["stay informed", "情報を得続ける"],
  ["emergency situation", "緊急事態"],
  ["in addition", "さらに、加えて"],
  ["in advance", "事前に、あらかじめ"],
  ["underground condition", "地下の状態", ["underground conditions"]],
  ["site", "場所、敷地"],
  ["destructive", "破壊的な"],
  ["shallow inland focus", "浅い直下型の震源"],
  ["active fault", "活断層", ["active faults"]],
  ["layered structure", "多層構造"],
  ["core", "核、コア"],
  ["mantle", "マントル"],
  ["crust", "地殻"],
  ["surface", "表面"],
  ["solid shell", "硬い殻"],
  ["be broken up into", "～に分かれている", ["broken up into"]],
  ["thick", "厚い"],
  ["tectonic plate", "テクトニック・プレート", ["tectonic plates"]],
  ["seismically active", "地震活動が活発な"],
  ["be located along", "～に沿って位置する", ["is located along"]],
  ["Ring of Fire", "環太平洋火山帯"],
  ["according to", "～によると"],
  ["include", "含む", ["includes"]],
  ["active volcano", "活火山", ["active volcanoes"]],
  ["be responsible for", "～の原因である", ["responsible for"]],
  ["subduction zone", "沈み込み帯", ["subduction zones"]],
  ["bend", "曲がる", ["bends"]],
  ["slide underneath", "～の下に滑り込む", ["slides underneath"]],
  ["curve down into", "曲がりながら～へ沈み込む", ["curving down into"]],
  ["archipelago", "群島、列島"],
  ["sink under", "～の下に沈み込む", ["sinking under"]],
  ["continental side", "大陸側"],
  ["warp", "ゆがむ、反る", ["warping"]],
  ["reach its limit", "限界に達する", ["reaches its limit"]],
  ["rebound", "反発する、跳ね返る", ["rebounds"]],
  ["produce", "生じさせる、生成する", ["produces", "producing"]],
  ["fault", "断層", ["faults"]],
  ["boundary", "境界", ["boundaries"]],
  ["not only A but also B", "AだけでなくBも", ["not only"]],
  ["chemical reaction", "化学反応", ["chemical reactions"]],
  ["process", "過程、プロセス"],
  ["substance", "物質", ["substances"]],
  ["convert A to B", "AをBに変換する", ["converted to"]],
  ["react together", "互いに反応する"],
  ["reactant", "反応物", ["reactants"]],
  ["product", "生成物", ["products"]],
  ["as a result of", "～の結果として"],
  ["chemical element", "化学元素", ["chemical elements"]],
  ["compound", "化合物", ["compounds"]],
  ["atom", "原子", ["atoms"]],
  ["chemically", "化学的に"],
  ["bond", "結合", ["bonds"]],
  ["property", "性質", ["properties"]],
  ["contain", "含む", ["contains"]],
  ["combination reaction", "結合反応、化合反応", ["combination reactions"]],
  ["combine", "結合する", ["combines", "combined"]],
  ["single product", "単一の生成物"],
  ["desired product", "目的の生成物"],
  ["synthesis", "合成"],
  ["formation", "形成"],
  ["synthesize", "合成する", ["synthesized"]],
  ["derive from", "～に由来する", ["derived from"]],
  ["source", "原料、供給源", ["sources"]],
  ["decomposition", "分解"],
  ["split into", "～に分かれる", ["splits into"]],
  ["break down into", "～に分解される", ["breaks down into"]],
  ["component element", "構成元素", ["component elements"]],
  ["molecule", "分子", ["molecules"]],
  ["oxidation", "酸化"],
  ["reduction", "還元"],
  ["reaction", "反応", ["reactions"]],
  ["oxygen", "酸素"],
  ["addition", "付加、追加"],
  ["removal", "除去、取り除くこと"],
  ["at the same time", "同時に"],
  ["oxidation-reduction reaction", "酸化還元反応"],
  ["redox reaction", "酸化還元反応、レドックス反応"],
  ["for short", "略して"],
  ["take an example", "例を挙げる"],
  ["heat", "加熱する"],
  ["copper", "銅"],
  ["react with", "～と反応する", ["reacts with"]],
  ["copper(II) oxide", "酸化銅(II)"],
  ["hydrogen gas", "水素ガス"],
  ["combine with", "～と結びつく", ["combines with"]],
  ["remain", "残る", ["remaining"]],
  ["explain", "説明する", ["explained"]],
  ["in terms of", "～の観点から"],
  ["electron", "電子", ["electrons"]],
  ["electron transfer", "電子移動"],
  ["lose", "失う", ["loses", "lost"]],
  ["accept", "受け取る", ["accepts", "accepted"]],
  ["oxidize", "酸化する", ["oxidized"]],
  ["reduce", "還元する", ["reduced"]],
  ["in other words", "言い換えれば"],
  ["loss", "喪失、失うこと"],
  ["gain", "獲得、得ること"],
  ["involve", "関与する、含む", ["involved"]],
  ["copper(II) sulfate", "硫酸銅(II)"],
  ["consist of", "～から成る", ["consists of"]],
  ["instead of", "～の代わりに"],
  ["sulfate", "硫酸塩、硫酸イオン"],
  ["zinc plate", "亜鉛板"],
  ["solution", "溶液"],
  ["ion", "イオン", ["ions"]],
  ["zinc metal", "金属亜鉛"],
  ["displace", "置き換える、置換する", ["displaces"]],
  ["positively charged", "正に帯電した"],
  ["donate", "与える、供与する", ["donates"]],
  ["reducing agent", "還元剤", ["reducing agents"]],
  ["alkali metal", "アルカリ金属", ["alkali metals"]],
  ["oxidizing agent", "酸化剤", ["oxidizing agents"]],
  ["common", "一般的な"],
  ["hydrogen peroxide", "過酸化水素"],
  ["halogen", "ハロゲン", ["halogens"]],
];

const escapeRegExp = (value: string) =>
  value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const findFormPosition = (sentence: string, form: string) => {
  const expression = new RegExp(`(^|[^a-z0-9])${escapeRegExp(form)}(?=$|[^a-z0-9])`, "i");
  const match = expression.exec(sentence);
  return match ? match.index : -1;
};

export const getSentenceVocabulary = (sentence: string): SentenceVocabulary[] =>
  glossary
    .map(([word, meaning, forms = []]) => {
      const positions = [word, ...forms]
        .map(form => findFormPosition(sentence, form))
        .filter(position => position >= 0);

      return {
        word,
        meaning,
        position: positions.length > 0 ? Math.min(...positions) : -1,
      };
    })
    .filter(item => item.position >= 0)
    .sort((left, right) => left.position - right.position)
    .map(({ word, meaning }) => ({ word, meaning }));
